#
# Theme setup
#
# If you use go mod to install your theme, you must use the URL of the theme.
# If your theme is in the themes directory, you just need to specify its name.
#
theme = "ananke"
#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

baseurl = "https://kg-llm.github.io"
title = "Knowledge Graphs & Large Language Models Workshop @ LREC 2026"
languageCode = "en-us"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
resourceDir = "../resources"
copyright = "KG-LLM-2026 Workshop Chairs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[pagination]
  pagerSize = 6

[languages]
  [languages.en]
    title = "Knowledge Graphs & Large Language Models Workshop @ LREC 2026"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Gilles SÃ©rasset"
  favicon = ""
  site_logo = ""
  description = "When Knowledge Graphs and Large Language Models play together"
  background_color_class = "bg-mid-gray"
  recent_posts_number = 6

#[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/GoHugoIO"

# Photo by Federico Grisorio: https://www.pexels.com/photo/view-of-turin-from-monte-dei-cappuccini-4117978/